version: '3'

services:
  app:
    build:
      context: ./docker
    image: surreymagpie/drupal7:latest
    ports:
      - 8080:80
      - 0443:443
    networks:
      - appnet
    volumes:
      - ./app/:/var/www/html

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
   appnet:
